### ISSUE TITLE
glove_words.txt

### ISSUE THREAD

**Issue by zhaocongyu** [muyeby/RGAT-ABSA#1]
作者您好，祝您新年快乐，请问您的代码中glove_words.txt在哪里能下载呢？如有打扰，非常抱歉，祝您生活愉快！

**Comment by PengboLiu** [comment]
您好，glove_word.txt就是把词向量的word提取出来了。脚本如下：
awk '{print $1}' glove.840B.300d.txt > glove_words.txt

**Comment by zhaocongyu** [comment]
谢谢您的解答，对我非常有帮助，感谢
