### ISSUE TITLE
about label_matrix

### ISSUE THREAD

**Issue by Cyich** [muyeby/RGAT-ABSA#2]
作者您好，关于
https://github.com/muyeby/RGAT-ABSA/blob/4c63891fa8eeda582b57629949b99aa9ff68d82f/common/tree.py#L8中的head_to_adj方法，我理解是为了生成两个矩阵，其中adj_matrix是一个0/1矩阵，代表token与token之间是否连通（其中token自身存在的自环边也置为1），另一个label_matrix是一个0/n矩阵（n < deprel_vocab_size），代表token与token之间的delrel_stoi，不知道我的理解是否正确呢？如果我的理解有误，还请您指明，谢谢啦~
如果我的理解是对的，那我有一个疑问，就是该文件的第35行：
**label_matrix[idx, idx] = 2**
为什么对label_matrix添加自环边时，对应的delrel_stoi为2呢？我查看了RGAT-ABSA/prepare_vocab.py 文件中的第62行：
**dep_vocab = Vocab(dep_counter, specials=["<pad>", "<self>", "<unk>"])**
如果按照specials的顺序（0、<pad> 1、<self>  2、<unk>），那么label_matrix[idx, idx] = 2不就代表自环边对应的label是<unk>了吗？也就是说，我认为对label_matrix添加自环边时，应该将主对角线赋值为<self>在vocab中的index，不知道我的理解是否有误呢？
烦请作者解答我的疑惑，谢谢啦~

**Comment by Cyich** [comment]
抱歉没有编辑好，对应部分如下：
为什么对label_matrix添加自环边时，对应的delrel_stoi为2呢？我查看了RGAT-ABSA/prepare_vocab.py 文件中的第62行：
`dep_vocab = Vocab(dep_counter, specials=["<pad>", "<self>", "<unk>"])`
如果按照specials的顺序（1、\<pad\> 2、\<self\> 3、\<unk\>），那么label_matrix[idx, idx] = 2不就代表自环边对应的label是\<unk\>了吗？

**Comment by goodbai-nlp** [comment]
您好，

感谢您的指正！这里确实是实现上的一个bug，自环边的label_id错了。后续我们会对此进行修复并重新评估模型性能。

**Comment by Cyich** [comment]
作者您好，感谢回复！

那实际上自环边的label_id应该是对应<self>的对吗？（另外，其实我理解自环边对模型性能的影响不会太大，望指点）

**Comment by goodbai-nlp** [comment]
您好，

自环边的 label_id 应该对应到 <self> 的id。另外按照我的理解和以往经验，这个影响应该不会很大。

**Comment by Cyich** [comment]
感谢回复，对我帮助很大！
